# Generated by Django 3.1.2 on 2020-10-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
